/;server.pro
/config.yml="texture"
grass, 0	
grass, 1	
grass, 2	
grass, 3	
grass, 4	
grass, 5	
grass, 6	
grass, 7	
grass, 8	
grass, 9	
grass, 10	
grass, 11	
grass, 12	
grass, 13	
grass, 14	
grass, 15	
grass, 16	
grass, 17	
grass, 18	
stone, 0	
stone, 1	
stone, 2	
stone, 3	
stone, 4	
stone, 5	
stone, 6	
cobblestone, 0	
cobblestone_mossy, 0	
stonebrick, 0	
stonebrick, 1	
stonebrick, 2	
stonebrick, 3	
bedrock, 0	
obsidian, 0	
clay, 0	
sand, 0	
sand, 1	
sandstone, 0	
sandstone, 1	
sandstone, 2	
sandstone, 3	
sandstone, 4	
redsandstone, 0	
redsandstone, 1	
redsandstone, 2	
redsandstone, 3	
redsandstone, 4	
gravel, 0	
dirt, 0	
dirt, 1	
dirt, 2	
planks, 0	
planks, 1	
planks, 2	
planks, 3	
planks, 4	
planks, 5	
stone_slab, 0	
stone_slab, 1	
brick, 0	
tnt, 0	
tnt, 1	
tnt, 2	
bookshelf, 0	
web, 0	
flower1, 0	
flower2, 0	
flower2, 1	
flower2, 2	
flower2, 3	
flower2, 4	
flower2, 5	
flower2, 6	
flower2, 7	
flower2, 8	
double_plant_bottom, 0	
double_plant_bottom, 1	
double_plant_bottom, 2	
double_plant_bottom, 3	
double_plant_bottom, 4	
double_plant_bottom, 5	
double_plant_top, 0	
double_plant_top, 1	
double_plant_top, 2	
double_plant_top, 3	
double_plant_top, 4	
double_plant_top, 5	
double_plant_carried, 0	
double_plant_carried, 1	
sunflower_additional, 0	
sunflower_additional, 1	
sapling, 0	
sapling, 1	
sapling, 2	
sapling, 3	
sapling, 4	
sapling, 5	
log, 0	
log, 1	
log, 2	
log, 3	
log, 4	
log, 5	
log, 6	
log, 7	
log2, 0	
log2, 1	
log2, 2	
log2, 3	
iron_block, 0	
gold_block, 0	
diamond_block, 0	
coal_block, 0	
lapis_block, 0	
emerald_block, 0	
redstone_block, 0	
quartz_block, 0	
quartz_block, 1	
quartz_block, 2	
quartz_block, 3	
quartz_block, 4	
quartz_block, 5	
quartz_block, 6	
mushroom_red, 0	
mushroom_brown, 0	
gold_ore, 0	
iron_ore, 0	
coal_ore, 0	
lapis_ore, 0	
diamond_ore, 0	
redstone_ore, 0	
emerald_ore, 0	
quartz_ore, 0	
tallgrass, 0	
tallgrass, 1	
tallgrass, 2	
tallgrass, 3	
tallgrass, 4	
crafting_table, 0	
crafting_table, 1	
crafting_table, 2	
furnace, 0	
furnace, 1	
furnace, 2	
furnace, 3	
stonecutter, 0	
stonecutter, 1	
stonecutter, 2	
stonecutter, 3	
sponge, 0	
glass, 0	
leaves, 0	
leaves, 1	
leaves, 2	
leaves, 3	
leaves, 4	
leaves, 5	
leaves, 6	
leaves, 7	
leaves_opaque, 0	
leaves_opaque, 1	
leaves_opaque, 2	
leaves_opaque, 3	
leaves2, 0	
leaves2, 1	
leaves2, 2	
leaves2, 3	
leaves_opaque2, 0	
leaves_opaque2, 1	
mob_spawner, 0	
snow, 0	
ice, 0	
ice_packed, 0	
cactus, 0	
cactus, 1	
cactus, 2	
reeds, 0	
jukebox_side, 0	
jukebox_top, 0	
waterlily, 0	
waterlily, 1	
mycelium, 0	
mycelium, 1	
torch_on, 0	
redstone_torch_on, 0	
redstone_torch_off, 0	
door, 0	
door, 1	
door, 2	
door, 3	
door, 4	
door, 5	
door, 6	
door, 7	
door, 8	
door, 9	
door, 10	
door, 11	
door, 12	
door, 13	
ladder, 0	
trapdoor, 0	
iron_trapdoor, 0	
iron_bars, 0	
farmland, 0	
farmland, 1	
wheat, 0	
wheat, 1	
wheat, 2	
wheat, 3	
wheat, 4	
wheat, 5	
wheat, 6	
wheat, 7	
grass_path, 0	
grass_path, 1	
lever, 0	
pumpkin, 0	
pumpkin, 1	
pumpkin, 2	
pumpkin, 3	
netherrack, 0	
nether_brick, 0	
nether_wart, 0	
nether_wart, 1	
nether_wart, 2	
soul_sand, 0	
glowstone, 0	
piston_top_sticky, 0	
piston_top_normal, 0	
piston_side, 0	
piston_inner, 0	
piston_bottom, 0	
melon, 0	
melon, 1	
melon_stem, 0	
melon_stem, 1	
pumpkin_stem, 0	
pumpkin_stem, 1	
rail_normal, 0	
rail_normal_turned, 0	
rail_golden, 0	
rail_golden_powered, 0	
rail_detector, 0	
rail_detector_powered, 0	
rail_activator, 0	
rail_activator_powered, 0	
bed, 0	
bed, 1	
bed, 2	
bed, 3	
bed, 4	
bed, 5	
cauldron_top, 0	
cauldron_inner, 0	
cauldron_side, 0	
cauldron_bottom, 0	
brewing_stand_base, 0	
brewing_stand, 0	
cake_bottom, 0	
cake_inner, 0	
cake_top, 0	
cake_side, 0	
mushroom_block, 0	
mushroom_block, 1	
mushroom_block, 2	
mushroom_block, 3	
vine, 0	
vine, 1	
repeater_off, 0	
repeater_on, 0	
glass_pane_top, 0	
end_stone, 0	
endframee, 0	
endframee, 1	
endframee, 2	
redstone_dust_cross, 0	
redstone_dust_cross_overlay, 0	
redstone_dust_line, 0	
redstone_dust_line_overlay, 0	
redstone_lamp_off, 0	
redstone_lamp_on, 0	
enchanting_table_bottom, 0	
enchanting_table_side, 0	
enchanting_table_top, 0	
dragon_egg, 0	
hayblock, 0	
hayblock, 1	
cocoa, 0	
cocoa, 1	
cocoa, 2	
trip_wire, 0	
trip_wire_source, 0	
command_block, 0	
itemframe_background, 0	
flower_pot, 0	
carrots, 0	
carrots, 1	
carrots, 2	
carrots, 3	
potatoes, 0	
potatoes, 1	
potatoes, 2	
potatoes, 3	
beetroot, 0	
beetroot, 1	
beetroot, 2	
beetroot, 3	
anvil_base, 0	
anvil_top_damaged_x, 0	
anvil_top_damaged_x, 1	
anvil_top_damaged_x, 2	
reactor_core, 0	
reactor_core, 1	
reactor_core, 2	
glowing_obsidian, 0	
destroy, 0	
destroy, 1	
destroy, 2	
destroy, 3	
destroy, 4	
destroy, 5	
destroy, 6	
destroy, 7	
destroy, 8	
destroy, 9	
chest_inventory, 0	
chest_inventory, 1	
chest_inventory, 2	
missing_tile, 0	
wool, 0	
wool, 1	
wool, 2	
wool, 3	
wool, 4	
wool, 5	
wool, 6	
wool, 7	
wool, 8	
wool, 9	
wool, 10	
wool, 11	
wool, 12	
wool, 13	
wool, 14	
wool, 15	
hardened_clay, 0	
stained_clay, 0	
stained_clay, 1	
stained_clay, 2	
stained_clay, 3	
stained_clay, 4	
stained_clay, 5	
stained_clay, 6	
stained_clay, 7	
stained_clay, 8	
stained_clay, 9	
stained_clay, 10	
stained_clay, 11	
stained_clay, 12	
stained_clay, 13	
stained_clay, 14	
stained_clay, 15	
fire, 0	
fire, 1	
still_water, 0	
still_lava, 0	
cauldron_water, 0	
portal, 0	
daylight_detector_side, 0	
daylight_detector_top, 0	
daylight_detector_inverted_top, 0	
noteblock, 0	
comparator_on, 0	
comparator_off, 0	
dispenser_front_horizontal, 0	
dispenser_front_vertical, 0	
dropper_front_horizontal, 0	
dropper_front_vertical, 0	
hopper_inside, 0	
hopper_outside, 0	
hopper_top, 0	
slime_block, 0	
flowing_water, 0	
flowing_lava, 0	
ITEMS
apple, 0	
apple_golden, 0	
arrow, 0	
axe, 0	
axe, 1	
axe, 2	
axe, 3	
axe, 4	
bed, 0	
beef_cooked, 0	
beef_raw, 0	
blaze_powder, 0	
blaze_rod, 0	
boat, 0	
boat, 1	
boat, 2	
boat, 3	
boat, 4	
boat, 5	
bone, 0	
book_enchanted, 0	
book_normal, 0	
book_writable, 0	
book_written, 0	
boots, 0	
boots, 1	
boots, 2	
boots, 3	
boots, 4	
bowl, 0	
bow_pulling, 0	
bow_pulling, 1	
bow_pulling, 2	
bow_standby, 0	
bread, 0	
brewing_stand, 0	
brick, 0	
bucket, 0	
bucket, 1	
bucket, 2	
bucket, 3	
cake, 0	
carrot, 0	
carrot_golden, 0	
carrot_on_a_stick, 0	
beetroot, 0	
cauldron, 0	
charcoal, 0	
chestplate, 0	
chestplate, 1	
chestplate, 2	
chestplate, 3	
chestplate, 4	
chicken_cooked, 0	
chicken_raw, 0	
clay_ball, 0	
coal, 0	
comparator, 0	
cookie, 0	
diamond, 0	
diamond_horse_armor, 0	
door_iron, 0	
door_wood, 0	
door_spruce, 0	
door_birch, 0	
door_jungle, 0	
door_acacia, 0	
door_darkoak, 0	
dye_powder, 0	
dye_powder, 1	
dye_powder, 2	
dye_powder, 3	
dye_powder, 4	
dye_powder, 5	
dye_powder, 6	
dye_powder, 7	
dye_powder, 8	
dye_powder, 9	
dye_powder, 10	
dye_powder, 11	
dye_powder, 12	
dye_powder, 13	
dye_powder, 14	
dye_powder, 15	
egg, 0	
emerald, 0	
empty_armor_slot_boots, 0	
empty_armor_slot_chestplate, 0	
empty_armor_slot_helmet, 0	
empty_armor_slot_leggings, 0	
ender_eye, 0	
ender_pearl, 0	
experience_bottle, 0	
feather, 0	
fireball, 0	
fireworks, 0	
fireworks_charge, 0	
fireworks_charge_overlay, 0	
fishing_rod, 0	
fishing_rod, 1	
fish_raw_cod, 0	
fish_raw_salmon, 0	
fish_raw_clown_fish, 0	
fish_raw_puffer_fish, 0	
fish_cooked_cod, 0	
fish_cooked_salmon, 0	
flint, 0	
flint_and_steel, 0	
flower_pot, 0	
ghast_tear, 0	
glowstone_dust, 0	
gold_horse_armor, 0	
gold_ingot, 0	
gold_nugget, 0	
gunpowder, 0	
helmet, 0	
helmet, 1	
helmet, 2	
helmet, 3	
helmet, 4	
hoe, 0	
hoe, 1	
hoe, 2	
hoe, 3	
hoe, 4	
hopper, 0	
iron_horse_armor, 0	
iron_ingot, 0	
item_frame, 0	
lead, 0	
leather, 0	
leggings, 0	
leggings, 1	
leggings, 2	
leggings, 3	
leggings, 4	
magma_cream, 0	
map_empty, 0	
map_filled, 0	
melon, 0	
melon_speckled, 0	
minecart_chest, 0	
minecart_furnace, 0	
minecart_hopper, 0	
minecart_normal, 0	
minecart_tnt, 0	
mushroom_stew, 0	
beetroot_soup, 0	
name_tag, 0	
netherbrick, 0	
nether_star, 0	
nether_wart, 0	
painting, 0	
paper, 0	
pickaxe, 0	
pickaxe, 1	
pickaxe, 2	
pickaxe, 3	
pickaxe, 4	
porkchop_cooked, 0	
porkchop_raw, 0	
potato, 0	
potato_baked, 0	
potato_poisonous, 0	
potion_bottle_drinkable, 0	
potion_bottle_drinkable, 1	
potion_bottle_drinkable, 2	
potion_bottle_drinkable, 3	
potion_bottle_drinkable, 4	
potion_bottle_drinkable, 5	
potion_bottle_drinkable, 6	
potion_bottle_drinkable, 7	
potion_bottle_drinkable, 8	
potion_bottle_drinkable, 9	
potion_bottle_drinkable, 10	
potion_bottle_drinkable, 11	
potion_bottle_drinkable, 12	
potion_bottle_drinkable, 13	
potion_bottle_drinkable, 14	
potion_bottle_drinkable, 15	
potion_bottle_drinkable, 16	
potion_bottle_drinkable, 17	
potion_bottle_drinkable, 18	
potion_bottle_drinkable, 19	
potion_bottle_drinkable, 20	
potion_bottle_drinkable, 21	
potion_bottle_drinkable, 22	
potion_bottle_drinkable, 23	
potion_bottle_empty, 0	
potion_bottle_splash, 0	
potion_bottle_splash, 1	
potion_bottle_splash, 2	
potion_bottle_splash, 3	
potion_bottle_splash, 4	
potion_bottle_splash, 5	
potion_bottle_splash, 6	
potion_bottle_splash, 7	
potion_bottle_splash, 8	
potion_bottle_splash, 9	
potion_bottle_splash, 10	
potion_bottle_splash, 11	
potion_bottle_splash, 12	
potion_bottle_splash, 13	
potion_bottle_splash, 14	
potion_bottle_splash, 15	
potion_bottle_splash, 16	
potion_bottle_splash, 17	
potion_bottle_splash, 18	
potion_bottle_splash, 19	
potion_bottle_splash, 20	
potion_bottle_splash, 21	
potion_bottle_splash, 22	
potion_bottle_splash, 23	
potion_overlay, 0	
pumpkin_pie, 0	
quartz, 0	
quiver, 0	
record_11, 0	
record_13, 0	
record_blocks, 0	
record_cat, 0	
record_chirp, 0	
record_far, 0	
record_mall, 0	
record_mellohi, 0	
record_stal, 0	
record_strad, 0	
record_wait, 0	
record_ward, 0	
redstone_dust, 0	
reeds, 0	
repeater, 0	
rotten_flesh, 0	
saddle, 0	
seeds_melon, 0	
seeds_pumpkin, 0	
seeds_wheat, 0	
seeds_beetroot, 0	
shears, 0	
shovel, 0	
shovel, 1	
shovel, 2	
shovel, 3	
shovel, 4	
sign, 0	
skull_creeper, 0	
skull_skeleton, 0	
skull_steve, 0	
skull_wither, 0	
skull_zombie, 0	
slimeball, 0	
snowball, 0	
spawn_egg, 0	
spawn_egg, 1	
spawn_egg, 2	
spawn_egg, 3	
spawn_egg, 4	
spawn_egg, 5	
spawn_egg, 6	
spawn_egg, 7	
spawn_egg, 8	
spawn_egg, 9	
spawn_egg, 10	
spawn_egg, 11	
spawn_egg, 12	
spawn_egg, 13	
spawn_egg, 14	
spawn_egg, 15	
spawn_egg, 16	
spawn_egg, 17	
spawn_egg, 18	
spawn_egg, 19	
spawn_egg, 20	
spawn_egg, 21	
spawn_egg, 22	
spawn_egg, 23	
spawn_egg, 24	
spawn_egg, 25	
spawn_egg, 26	
spider_eye, 0	
spider_eye_fermented, 0	
stick, 0	
string, 0	
sugar, 0	
sword, 0	
sword, 1	
sword, 2	
sword, 3	
sword, 4	
wheat, 0	
clock_item, 0	
compass_item, 0	
rabbit_cooked, 0	
rabbit_foot, 0	
rabbit_hide, 0	
rabbit, 0	
rabbit_stew, 0	
lever, 0	
camera, 0
